language: ruby
rvm:
  - "1.9.3"
  - "2.1.0"
# http://docs.travis-ci.com/user/build-configuration/#Specify-branches-to-build
# branches:
#   except:
#     - master
#   only:
#     - release/roxy/master
gemfile: chef/cookbooks/pacemaker/Gemfile
# overridden by install: value
#bundler_args: --without development
install: cd chef/cookbooks/pacemaker && bundle install --without development
script: exec rspec
