language: ruby
sudo: false

matrix:
  include:
    - rvm: 2.1.0
      gemfile: Gemfile
      env: RAKEDIR=.
    - rvm: 2.1.0
      gemfile: chef/cookbooks/pacemaker/Gemfile
      env: RAKEDIR=chef/cookbooks/pacemaker

script: cd $RAKEDIR && bundle exec rake
bundler_args: --without development
